### ISSUE TITLE
2 failed unit tests (popit_search)

### ISSUE THREAD

**Issue by leowmjw** [Sinar/popit_ng#102]
Two unit tests failed:

```
======================================================================
ERROR: popit_search.tests.test_search_views (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: popit_search.tests.test_search_views
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/vagrant/popit_search/tests/test_search_views.py", line 5, in <module>
    from mock import patch
  File "/usr/local/lib/python2.7/dist-packages/mock/__init__.py", line 2, in <module>
    import mock.mock as _mock
  File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 68, in <module>
    from six import wraps
ImportError: cannot import name wraps


======================================================================
ERROR: popit_search.tests.tests_search_util (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: popit_search.tests.tests_search_util
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/vagrant/popit_search/tests/tests_search_util.py", line 6, in <module>
    from mock import patch
  File "/usr/local/lib/python2.7/dist-packages/mock/__init__.py", line 2, in <module>
    import mock.mock as _mock
  File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 68, in <module>
    from six import wraps
ImportError: cannot import name wraps

```

**Comment by sweemeng** [comment]
Tell me how you run the test? also give me the output of pip freeze

**Comment by leowmjw** [comment]
Used what I read (not Django expert :P) is the standard test command:
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ ./manage.py test
Creating test database for alias 'default'...
...
```

Here is output of "pip freeze"
```
FAILED (errors=2)
Destroying test database for alias 'default'...
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ pip freeze
Cheetah==2.4.4
Django==1.9
Landscape-Client==14.12
PAM==0.4.2
PyYAML==3.10
SecretStorage==2.0.0
Twisted-Core==13.2.0
Twisted-Names==13.2.0
Twisted-Web==13.2.0
apt-xapian-index==0.45
argparse==1.2.1
chardet==2.0.1
cloud-init==0.7.5
colorama==0.2.5
configobj==4.7.2
django-cors-headers==1.1.0
django-hvad==1.4.0
django-rosetta==0.7.8
djangorestframework==3.3.1
elasticsearch==2.1.0
funcsigs==0.4
gunicorn==19.4.1
html5lib==0.999
httplib2==0.8
jsonpatch==1.3
jsonpointer==1.0
keyring==3.5
launchpadlib==1.10.2
lazr.restfulclient==0.13.3
lazr.uri==1.0.3
microsofttranslator==0.7
mock==1.3.0
oauth==1.0.1
pbr==1.8.1
polib==1.0.7
prettytable==0.7.2
psycopg2==2.6.1
pyOpenSSL==0.13
pycrypto==2.6.1
pycurl==7.19.3
pygobject==3.12.0
pyserial==2.6
python-apt==0.9.3.5ubuntu2
python-debian==0.1.21-nmu2ubuntu2
requests==2.2.1
simplejson==3.3.1
six==1.5.2
ssh-import-id==3.21
urllib3==1.14
wadllib==1.3.2
wheel==0.24.0
wsgiref==0.1.2
zope.interface==4.0.5
```

**Comment by sweemeng** [comment]
Updated six module, checkout hotfix/20160204-update-six-modules. Test it. Work fine for me, verify anyway

**Comment by sweemeng** [comment]
close for now
