### ISSUE TITLE
Serializer data property broken if queryset is used

### ISSUE THREAD

**Issue by sweemeng** [Sinar/popit_ng#41]
```
>>> from popit.models import *
>>> from popit.serializers import *
>>> persons = Person.objects.untranslated().all()
>>> serializer = PersonSerializer(persons, language="en")
>>> serializer.data
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 503, in data
    ret = super(Serializer, self).data
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 239, in data
    self._data = self.to_representation(self.instance)
  File "/vagrant/popit/serializers/person.py", line 159, in to_representation
    data = super(PersonSerializer, self).to_representation(instance)
  File "/usr/local/lib/python2.7/dist-packages/hvad/contrib/restframework/serializers.py", line 180, in to_representation
    translation = load_translation(instance, language, enforce)
  File "/usr/local/lib/python2.7/dist-packages/hvad/utils.py", line 68, in load_translation
    trans_model = instance._meta.translations_model
AttributeError: 'SelfJoinFallbackQueryset' object has no attribute '_meta'
```
Fix to_representation method, add unittest

**Comment by sweemeng** [comment]
Invalid, reason many parameter need too be used
