### ISSUE TITLE
Person object must have related translation

### ISSUE THREAD

**Issue by sweemeng** [Sinar/popit_ng#54]
Find out pathway where this happen
```
>>> person_ = Person.objects.language("en").get(id="545e42445222837c2c05874f")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/apps/popit_env/local/lib/python2.7/site-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
DoesNotExist: PersonTranslation matching query does not exist.
>>> 
```

**Comment by sweemeng** [comment]
cannot reproduce, closing
